name: nontracking-customer-card
static_sites:
- name: site
  github:
    repo: trichling/NonTrackingCustomerCard
    branch: main
    deploy_on_push: true
  dockerfile_path: src/NontrackingCustomerCard.Client/Dockerfile 
  output_dir: /output/wwwroot
  index_document: index.html
  catchall_document: index.html